### ISSUE TITLE
Screen is not outputting characters

### ISSUE THREAD

**Issue by DarienRamcharan** [kiwih/pic16f877a-ssd1306-oled#2]
Hello good day sir, I've downloaded your code exactly how it is except changing the crystal frequency to match mine but my screen seems to be displaying gibberish, I've changed nothing else in your code besides that crystal frequency.I have no clue what I am doing wrong, I am new to the i2c protocol and interfacing Oleds etc. so any kinda of help will be great. I think I have your exact set up on the breadboard as well except for crystals of different speeds. I attached a screenshot of what is being displayed and the exact screen and micro-controller used.

Oled Screen:
https://www.amazon.com/dp/B08T9LH9J6?psc=1&ref=ppx_yo2_dt_b_product_details
PIC16F877A:
https://www.digikey.com/en/products/detail/microchip-technology/PIC16F877A-I-P/446143

![20211004_164336](https://user-images.githubusercontent.com/22904082/135922843-fb20a074-599c-4c49-94d2-03a2b0ac824b.jpg)
.

**Comment by kiwih** [comment]
Usually the first step here would be to check the wiring again and again. If you're certain the wiring is correct,
1. check the oled is working - try run it with an arduino or other device and make sure it works with them 
2. check the pic is working - try a simpler program to just blink an LED or something
3. check the breadboard is good - using a multimeter, check for shorts etc

**Comment by DarienRamcharan** [comment]
> 
> 
> Usually the first step here would be to check the wiring again and again. If you're certain the wiring is correct,
> 
>     1. check the oled is working - try run it with an arduino or other device and make sure it works with them
> 
>     2. check the pic is working - try a simpler program to just blink an LED or something
> 
>     3. check the breadboard is good - using a multimeter, check for shorts etc

Hey, I'd first like to thank for replying! I made sure and did all of the above steps, I even tried 2 or 3 micro-controllers ( I bought 10 PIC16F877A in case I destroyed some while learning ). Honestly the Oled is kind of sketchy in the sense that Amazon claims that it is I2c compatible and uses a SSD1306 module but when you scroll down it then states the following :

https://www.amazon.com/dp/B08T9LH9J6?psc=1&ref=ppx_yo2_dt_b_product_details

Specifications:

Display Size: 1.3"
Text Color: Blue
Resolution: 128x64
Driver IC: SSD1106
Input Voltage: 3.3V/5V
Pins:
GND: (Ground)
VCC: (Power)
SCL: (Clock)
SDA: (Data Cable)

I posted here the i2c bus properly working and communicating between 2 PIC16F877A microcontroller using code found on Deepblue's website.

https://deepbluembedded.com/i2c-communication-protocol-tutorial-pic/

Below is a small video displaying that the micro-controller and I2c bus in fact works as intended.

https://user-images.githubusercontent.com/22904082/136121908-a06e40a2-24b7-4c48-87ff-c2176798ac46.mp4

Honestly I think it's probably the sketchy screen, if you can link me the exact one that you used maybe I can order it and test it out to see if that is the issue, however I will try it out first with the Arduino since I actually own one of those or possibly even better if you can point me in the direction of what type or size of screen would be easier to implement with the PIC16F877A. I am extremely new to this but I am learning a lot.

**Comment by kiwih** [comment]
It does sound like you're doing everything correctly! I can't comment on the exact screen that I used but it was something from Amazon or Aliexpress or Ebay or something like that... Do check your screen with another device, I'm pretty confident in my code (I mean I got the pictures to prove it, as you can see!)

**Comment by jtannenba** [comment]
I thought the sceen address s/b 0x3C?  You  have 0x78?  The oled he has, though Amazon says SSD1306, I believe is the SH1106.  I get the same screen with my 1.3" oled which I believe is the SH1106.
