### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jtannenba** [kiwih/pic16f877a-ssd1306-oled#3]
Not used to MPLABX.  Trying to compile this and get this error:   :0:: error: (500) undefined symbols:
	_I2C_Write(dist/default/production\Oled.X.production.o) _I2C_Begin(dist/default/production\Oled.X.production.o) _I2C_End(dist/default/production\Oled.X.production.o) _I2C_Initialize(dist/default/production\Oled.X.production.o) 
(908) exit status = 1
I don't see where it is getting _I2C_...  Since all the calls are without the proceeding underline.

I've tried with MPLABX 6.0 and 6,15 and get the same error.

Suggestions?

Thank you,
Joe

**Comment by jtannenba** [comment]
Went back to 3.35 and retried it and it compiled!  Found I had to change the address to 0x3c, but still no display.  Pulseview looks like nothing is going?  It doesn't look like anything is going on. Tried both the original and the branch.

I have a PIC16F877A on a project boad with 8mhz crystal. I'm using 4.7k resistors for pullups on SCL and SDA.  I'm at a total loss.

Edit:  Oops! the way C does the address 0x78 was correct, my bad

**Comment by jtannenba** [comment]
Got it working.  It's in MPLABX 6.1.5,; XC8 Compiler 1.38;PIC16F877a DFU 1.6.156. and removed I2C.c & h and Common.h. Used
B.Aswinth Raj's PIC16F877a_I2C.h instead. I attached the zipped project for info
[oled.zip](https://github.com/kiwih/pic16f877a-ssd1306-oled/files/13941066/oled.zip)

Thank you.
Joe

**Comment by kiwih** [comment]
Thanks for putting in the updates Joe - I haven't got a setup which can run this project right now so I'm glad you got it working!
